/**
 * Generated by Babylon.js Editor
 */

import { loadScene } from "babylonjs-editor-tools";
import * as scripts from "./scripts";

export const scriptsMap = {
	"scripts": scripts
};

export { loadScene };
